"""change password

Revision ID: 2c609f7fd46
Revises: 69b122f64a
Create Date: 2015-12-12 18:54:59.187012

"""

# revision identifiers, used by Alembic.
revision = '2c609f7fd46'
down_revision = '69b122f64a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
