"""initial migration

Revision ID: 4fd5d8000d4
Revises: 849907c4b2
Create Date: 2015-12-06 23:58:00.000260

"""

# revision identifiers, used by Alembic.
revision = '4fd5d8000d4'
down_revision = '849907c4b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
