"""Log

Revision ID: 69b122f64a
Revises: 4fd5d8000d4
Create Date: 2015-12-07 19:24:30.532124

"""

# revision identifiers, used by Alembic.
revision = '69b122f64a'
down_revision = '4fd5d8000d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
