"""initial migration

Revision ID: 849907c4b2
Revises: None
Create Date: 2015-12-06 18:53:56.002219

"""

# revision identifiers, used by Alembic.
revision = '849907c4b2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('username', table_name='users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    ### end Alembic commands ###
