"""add markdown post

Revision ID: 84acde3f0dae
Revises: 8a20b0055e44
Create Date: 2016-01-04 22:17:36.902292

"""

# revision identifiers, used by Alembic.
revision = '84acde3f0dae'
down_revision = '8a20b0055e44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
